auto_reload: 0m
service:
  host: localhost
  http_port: 9090
  ws_port: 9091
  pid_file: {{ .octopus_home }}/tmp/pids/octopus_test.pid
security:
  dashboard:
    username: root
    password: waterISwide
    token_expiry: 24h
    aes:
      key: abcdefg123456789
      iv: abcdefg123456789
  ssl:
    certfile:
    keyfile:
connections:
  registry: memory
  nshards: 4
  init_shard_size: 128
  request_queue_size: 8
  expiry: &expiry 300s
  timeouts:
    write: 2s
    read: *expiry
    request: 2s
    response: 8s
  buffer_sizes:
    read: 1024
    write: 1024
indices:
  host: localhost
  port: 9200
  number_of_shards: 8
  number_of_replicas: 0
  ttl_enabled: true
  ttl: '336h'
database:
  db_type: sqlite3
  db_file: {{ .octopus_home }}/db/octopus_test.db
  logging: false
logging:
  octopus:
    filename: {{ .octopus_home }}/logs/test/octopus.log
    maxsize: 1024
    maxage: 7
    maxbackups: 5
    level: debug
    buffer_size: 0
  indices:
    filename: {{ .octopus_home }}/logs/test/indices.log
    maxsize: 1024
    maxage: 7
    maxbackups: 5
    level: debug
    buffer_size: 0
  database:
    filename: {{ .octopus_home }}/logs/test/db.log
    maxsize: 1024
    maxage: 7
    maxbackups: 5
    level: debug
    buffer_size: 0
